/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ProjectId = bigint;
export interface InventionProject {
    id: ProjectId;
    claims: string;
    status: InventionStatus;
    aiAnalysis?: AIAnalysis;
    title: string;
    features: string;
    ownerId: string;
    createdAt: bigint;
    updatedAt: bigint;
    solution: string;
    problem: string;
}
export interface InventionProjectInput {
    claims: string;
    status: InventionStatus;
    aiAnalysis?: AIAnalysis;
    title: string;
    features: string;
    ownerId: string;
    solution: string;
    problem: string;
}
export interface AIAnalysis {
    suggestions: Array<string>;
    readinessScore: bigint;
    noveltyChecklist: Array<string>;
}
export enum InventionStatus {
    submitted = "submitted",
    readyToSubmit = "readyToSubmit",
    inReview = "inReview",
    draft = "draft"
}
export interface backendInterface {
    createProject(input: InventionProjectInput): Promise<ProjectId>;
    deleteProject(projectId: ProjectId): Promise<void>;
    getAllProjects(): Promise<Array<InventionProject>>;
    getMostRecentlyUpdatedProject(): Promise<InventionProject | null>;
    getProject(projectId: ProjectId): Promise<InventionProject>;
    getProjectsByStatus(status: InventionStatus): Promise<Array<InventionProject>>;
    updateProject(projectId: ProjectId, input: InventionProjectInput): Promise<void>;
}
import type { AIAnalysis as _AIAnalysis, InventionProject as _InventionProject, InventionProjectInput as _InventionProjectInput, InventionStatus as _InventionStatus, ProjectId as _ProjectId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createProject(arg0: InventionProjectInput): Promise<ProjectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_InventionProjectInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_InventionProjectInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteProject(arg0: ProjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getAllProjects(): Promise<Array<InventionProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMostRecentlyUpdatedProject(): Promise<InventionProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMostRecentlyUpdatedProject();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMostRecentlyUpdatedProject();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: ProjectId): Promise<InventionProject> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_InventionProject_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_InventionProject_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsByStatus(arg0: InventionStatus): Promise<Array<InventionProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByStatus(to_candid_InventionStatus_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByStatus(to_candid_InventionStatus_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: ProjectId, arg1: InventionProjectInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_InventionProjectInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_InventionProjectInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_InventionProject_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventionProject): InventionProject {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_InventionStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventionStatus): InventionStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AIAnalysis]): AIAnalysis | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventionProject]): InventionProject | null {
    return value.length === 0 ? null : from_candid_InventionProject_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    claims: string;
    status: _InventionStatus;
    aiAnalysis: [] | [_AIAnalysis];
    title: string;
    features: string;
    ownerId: string;
    createdAt: bigint;
    updatedAt: bigint;
    solution: string;
    problem: string;
}): {
    id: ProjectId;
    claims: string;
    status: InventionStatus;
    aiAnalysis?: AIAnalysis;
    title: string;
    features: string;
    ownerId: string;
    createdAt: bigint;
    updatedAt: bigint;
    solution: string;
    problem: string;
} {
    return {
        id: value.id,
        claims: value.claims,
        status: from_candid_InventionStatus_n8(_uploadFile, _downloadFile, value.status),
        aiAnalysis: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.aiAnalysis)),
        title: value.title,
        features: value.features,
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        solution: value.solution,
        problem: value.problem
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    readyToSubmit: null;
} | {
    inReview: null;
} | {
    draft: null;
}): InventionStatus {
    return "submitted" in value ? InventionStatus.submitted : "readyToSubmit" in value ? InventionStatus.readyToSubmit : "inReview" in value ? InventionStatus.inReview : "draft" in value ? InventionStatus.draft : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventionProject>): Array<InventionProject> {
    return value.map((x)=>from_candid_InventionProject_n6(_uploadFile, _downloadFile, x));
}
function to_candid_InventionProjectInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventionProjectInput): _InventionProjectInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_InventionStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventionStatus): _InventionStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    claims: string;
    status: InventionStatus;
    aiAnalysis?: AIAnalysis;
    title: string;
    features: string;
    ownerId: string;
    solution: string;
    problem: string;
}): {
    claims: string;
    status: _InventionStatus;
    aiAnalysis: [] | [_AIAnalysis];
    title: string;
    features: string;
    ownerId: string;
    solution: string;
    problem: string;
} {
    return {
        claims: value.claims,
        status: to_candid_InventionStatus_n3(_uploadFile, _downloadFile, value.status),
        aiAnalysis: value.aiAnalysis ? candid_some(value.aiAnalysis) : candid_none(),
        title: value.title,
        features: value.features,
        ownerId: value.ownerId,
        solution: value.solution,
        problem: value.problem
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventionStatus): {
    submitted: null;
} | {
    readyToSubmit: null;
} | {
    inReview: null;
} | {
    draft: null;
} {
    return value == InventionStatus.submitted ? {
        submitted: null
    } : value == InventionStatus.readyToSubmit ? {
        readyToSubmit: null
    } : value == InventionStatus.inReview ? {
        inReview: null
    } : value == InventionStatus.draft ? {
        draft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
