import { InventionProject } from '../backend';
import { downloadTextFile } from './projectExport';

function formatStatus(status: string): string {
  const map: Record<string, string> = {
    draft: 'Draft',
    inReview: 'In Review',
    readyToSubmit: 'Ready to Submit',
    submitted: 'Submitted',
  };
  return map[status] || status;
}

function formatDate(timestamp: bigint): string {
  return new Date(Number(timestamp) / 1_000_000).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export function generateLawyerPackage(project: InventionProject, coverNote: string): string {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const lines: string[] = [
    '╔═══════════════════════════════════════════════════════════════╗',
    '║           PATENT ATTORNEY SUBMISSION PACKAGE                  ║',
    '║                  Generated by PatentForge AI                  ║',
    '╚═══════════════════════════════════════════════════════════════╝',
    '',
    `Date: ${today}`,
    `Re: Invention Disclosure — ${project.title}`,
    `Status: ${formatStatus(String(project.status))}`,
    '',
    '═══════════════════════════════════════════════════════════════',
    'SECTION 1: COVER NOTE',
    '═══════════════════════════════════════════════════════════════',
    '',
    coverNote || 'Dear Patent Attorney,\n\nPlease find enclosed the invention disclosure for the above-referenced invention. I am seeking your assistance in evaluating the patentability of this invention and preparing a patent application.\n\nThank you for your time and consideration.',
    '',
    '═══════════════════════════════════════════════════════════════',
    'SECTION 2: INVENTION IDENTIFICATION',
    '═══════════════════════════════════════════════════════════════',
    '',
    `Invention Title: ${project.title}`,
    `Project ID: ${project.id.toString()}`,
    `First Documented: ${formatDate(project.createdAt)}`,
    `Last Updated: ${formatDate(project.updatedAt)}`,
    '',
    '═══════════════════════════════════════════════════════════════',
    'SECTION 3: TECHNICAL DISCLOSURE',
    '═══════════════════════════════════════════════════════════════',
    '',
    '3.1 PROBLEM STATEMENT',
    '───────────────────────────────────────────────────────────────',
    project.problem || '(Not provided)',
    '',
    '3.2 PROPOSED SOLUTION',
    '───────────────────────────────────────────────────────────────',
    project.solution || '(Not provided)',
    '',
    '3.3 KEY FEATURES AND NOVEL ASPECTS',
    '───────────────────────────────────────────────────────────────',
    project.features || '(Not provided)',
    '',
    '═══════════════════════════════════════════════════════════════',
    'SECTION 4: PATENT CLAIMS (DRAFT)',
    '═══════════════════════════════════════════════════════════════',
    '',
    'NOTE: The following claims are draft claims prepared by the inventor.',
    'These should be reviewed and refined by a registered patent attorney.',
    '',
    project.claims || '(No claims drafted yet)',
    '',
  ];

  if (project.aiAnalysis) {
    lines.push('═══════════════════════════════════════════════════════════════');
    lines.push('SECTION 5: AI PATENTABILITY ANALYSIS');
    lines.push('═══════════════════════════════════════════════════════════════');
    lines.push('');
    lines.push(`Overall Readiness Score: ${project.aiAnalysis.readinessScore.toString()}% complete`);
    lines.push('');
    lines.push('5.1 NOVELTY CHECKLIST');
    lines.push('───────────────────────────────────────────────────────────────');
    project.aiAnalysis.noveltyChecklist.forEach((item, i) => {
      lines.push(`  ${i + 1}. ${item}`);
    });
    lines.push('');
    lines.push('5.2 RECOMMENDED IMPROVEMENTS');
    lines.push('───────────────────────────────────────────────────────────────');
    project.aiAnalysis.suggestions.forEach((item, i) => {
      lines.push(`  ${i + 1}. ${item}`);
    });
    lines.push('');
  }

  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('SECTION 6: INVENTOR CERTIFICATION');
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('');
  lines.push('I hereby certify that I am the original inventor of the above-described');
  lines.push('invention and that the information provided is accurate and complete to');
  lines.push('the best of my knowledge.');
  lines.push('');
  lines.push('Inventor Signature: _______________________________');
  lines.push('');
  lines.push(`Date: ${today}`);
  lines.push('');
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('CONFIDENTIAL — ATTORNEY-CLIENT PRIVILEGED COMMUNICATION');
  lines.push('Generated by PatentForge AI — Universal Invention to Patent Platform');
  lines.push('═══════════════════════════════════════════════════════════════');

  return lines.join('\n');
}

export function downloadLawyerPackage(project: InventionProject, coverNote: string): void {
  const content = generateLawyerPackage(project, coverNote);
  const safeTitle = project.title.replace(/[^a-zA-Z0-9]/g, '-').substring(0, 30);
  const dateStr = new Date().toISOString().split('T')[0];
  downloadTextFile(content, `LawyerPackage-${safeTitle}-${dateStr}.txt`);
}
