import { InventionProject } from '../backend';

function formatStatus(status: string): string {
  const map: Record<string, string> = {
    draft: 'Draft',
    inReview: 'In Review',
    readyToSubmit: 'Ready to Submit',
    submitted: 'Submitted',
  };
  return map[status] || status;
}

function formatDate(timestamp: bigint): string {
  return new Date(Number(timestamp) / 1_000_000).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export function exportProjectAsText(project: InventionProject): string {
  const lines: string[] = [
    '═══════════════════════════════════════════════════════════════',
    '                    PATENTFORGE AI EXPORT',
    '═══════════════════════════════════════════════════════════════',
    '',
    `TITLE: ${project.title}`,
    `STATUS: ${formatStatus(String(project.status))}`,
    `CREATED: ${formatDate(project.createdAt)}`,
    `LAST UPDATED: ${formatDate(project.updatedAt)}`,
    `PROJECT ID: ${project.id.toString()}`,
    '',
    '───────────────────────────────────────────────────────────────',
    'PROBLEM BEING SOLVED',
    '───────────────────────────────────────────────────────────────',
    project.problem || '(Not provided)',
    '',
    '───────────────────────────────────────────────────────────────',
    'PROPOSED SOLUTION',
    '───────────────────────────────────────────────────────────────',
    project.solution || '(Not provided)',
    '',
    '───────────────────────────────────────────────────────────────',
    'KEY FEATURES',
    '───────────────────────────────────────────────────────────────',
    project.features || '(Not provided)',
    '',
    '───────────────────────────────────────────────────────────────',
    'CLAIMS',
    '───────────────────────────────────────────────────────────────',
    project.claims || '(Not provided)',
    '',
  ];

  if (project.aiAnalysis) {
    lines.push('───────────────────────────────────────────────────────────────');
    lines.push('AI ANALYSIS');
    lines.push('───────────────────────────────────────────────────────────────');
    lines.push(`Readiness Score: ${project.aiAnalysis.readinessScore.toString()}%`);
    lines.push('');
    lines.push('Novelty Checklist:');
    project.aiAnalysis.noveltyChecklist.forEach((item, i) => {
      lines.push(`  ${i + 1}. ${item}`);
    });
    lines.push('');
    lines.push('Suggestions:');
    project.aiAnalysis.suggestions.forEach((item, i) => {
      lines.push(`  ${i + 1}. ${item}`);
    });
    lines.push('');
  }

  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('Generated by PatentForge AI — Universal Invention to Patent Platform');
  lines.push(`Export Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push('═══════════════════════════════════════════════════════════════');

  return lines.join('\n');
}

export function downloadTextFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
