/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InventionStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'readyToSubmit' : IDL.Null,
  'inReview' : IDL.Null,
  'draft' : IDL.Null,
});
export const AIAnalysis = IDL.Record({
  'suggestions' : IDL.Vec(IDL.Text),
  'readinessScore' : IDL.Nat,
  'noveltyChecklist' : IDL.Vec(IDL.Text),
});
export const InventionProjectInput = IDL.Record({
  'claims' : IDL.Text,
  'status' : InventionStatus,
  'aiAnalysis' : IDL.Opt(AIAnalysis),
  'title' : IDL.Text,
  'features' : IDL.Text,
  'ownerId' : IDL.Text,
  'solution' : IDL.Text,
  'problem' : IDL.Text,
});
export const ProjectId = IDL.Nat;
export const InventionProject = IDL.Record({
  'id' : ProjectId,
  'claims' : IDL.Text,
  'status' : InventionStatus,
  'aiAnalysis' : IDL.Opt(AIAnalysis),
  'title' : IDL.Text,
  'features' : IDL.Text,
  'ownerId' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'solution' : IDL.Text,
  'problem' : IDL.Text,
});

export const idlService = IDL.Service({
  'createProject' : IDL.Func([InventionProjectInput], [ProjectId], []),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(InventionProject)], ['query']),
  'getMostRecentlyUpdatedProject' : IDL.Func(
      [],
      [IDL.Opt(InventionProject)],
      ['query'],
    ),
  'getProject' : IDL.Func([ProjectId], [InventionProject], ['query']),
  'getProjectsByStatus' : IDL.Func(
      [InventionStatus],
      [IDL.Vec(InventionProject)],
      ['query'],
    ),
  'updateProject' : IDL.Func([ProjectId, InventionProjectInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InventionStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'readyToSubmit' : IDL.Null,
    'inReview' : IDL.Null,
    'draft' : IDL.Null,
  });
  const AIAnalysis = IDL.Record({
    'suggestions' : IDL.Vec(IDL.Text),
    'readinessScore' : IDL.Nat,
    'noveltyChecklist' : IDL.Vec(IDL.Text),
  });
  const InventionProjectInput = IDL.Record({
    'claims' : IDL.Text,
    'status' : InventionStatus,
    'aiAnalysis' : IDL.Opt(AIAnalysis),
    'title' : IDL.Text,
    'features' : IDL.Text,
    'ownerId' : IDL.Text,
    'solution' : IDL.Text,
    'problem' : IDL.Text,
  });
  const ProjectId = IDL.Nat;
  const InventionProject = IDL.Record({
    'id' : ProjectId,
    'claims' : IDL.Text,
    'status' : InventionStatus,
    'aiAnalysis' : IDL.Opt(AIAnalysis),
    'title' : IDL.Text,
    'features' : IDL.Text,
    'ownerId' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'solution' : IDL.Text,
    'problem' : IDL.Text,
  });
  
  return IDL.Service({
    'createProject' : IDL.Func([InventionProjectInput], [ProjectId], []),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(InventionProject)], ['query']),
    'getMostRecentlyUpdatedProject' : IDL.Func(
        [],
        [IDL.Opt(InventionProject)],
        ['query'],
      ),
    'getProject' : IDL.Func([ProjectId], [InventionProject], ['query']),
    'getProjectsByStatus' : IDL.Func(
        [InventionStatus],
        [IDL.Vec(InventionProject)],
        ['query'],
      ),
    'updateProject' : IDL.Func([ProjectId, InventionProjectInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };