/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIAnalysis {
  'suggestions' : Array<string>,
  'readinessScore' : bigint,
  'noveltyChecklist' : Array<string>,
}
export interface InventionProject {
  'id' : ProjectId,
  'claims' : string,
  'status' : InventionStatus,
  'aiAnalysis' : [] | [AIAnalysis],
  'title' : string,
  'features' : string,
  'ownerId' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'solution' : string,
  'problem' : string,
}
export interface InventionProjectInput {
  'claims' : string,
  'status' : InventionStatus,
  'aiAnalysis' : [] | [AIAnalysis],
  'title' : string,
  'features' : string,
  'ownerId' : string,
  'solution' : string,
  'problem' : string,
}
export type InventionStatus = { 'submitted' : null } |
  { 'readyToSubmit' : null } |
  { 'inReview' : null } |
  { 'draft' : null };
export type ProjectId = bigint;
export interface _SERVICE {
  'createProject' : ActorMethod<[InventionProjectInput], ProjectId>,
  'deleteProject' : ActorMethod<[ProjectId], undefined>,
  'getAllProjects' : ActorMethod<[], Array<InventionProject>>,
  'getMostRecentlyUpdatedProject' : ActorMethod<[], [] | [InventionProject]>,
  'getProject' : ActorMethod<[ProjectId], InventionProject>,
  'getProjectsByStatus' : ActorMethod<
    [InventionStatus],
    Array<InventionProject>
  >,
  'updateProject' : ActorMethod<[ProjectId, InventionProjectInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];